src/webapps/webapps/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('cognita.urls_shiqiw')),
    url(r'^', include('cognita.urls_xinyangg')),
    url(r'^', include('cognita.urls_mohanf')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

src/webapps/cognita/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.utils import timezone

from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MaxValueValidator
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Tag(models.Model):
    tag_content = models.CharField(max_length=20, blank=False)

    def __unicode__(self):
        return self.tag_content


class Course(models.Model):
    Category_CHOICES = (
        ('CS', 'Computer Science'),
        ('MATH', 'Mathematics'),
        ('ART', 'Art'),
        ('BUS', 'Business'),
        ('SCI', 'Natural Science'),
        ('SSCI', 'Social Science'),
        ('LIT', 'Literature'),
        ('UCL', 'Unclassified'),
    )

    title = models.CharField(max_length=255, blank=False, null=False)
    published = models.BooleanField(blank=False, null=False, default=False)
    creator = models.ForeignKey(User, blank=False, null=False, related_name='course_created')
    creator_info = models.TextField()
    description = models.TextField()
    students = models.ManyToManyField(User, related_name='course_taking', blank=True)
    category = models.CharField(blank=False, null=False, max_length=5, choices=Category_CHOICES, default='UCL')
    course_image = models.ImageField(blank=True, upload_to="course_image")
    created_at = models.DateTimeField(default=timezone.now)
    tags = models.ManyToManyField(Tag, blank=True, related_name='tagged_course')

    def __unicode__(self):
        return self.title


class Module(models.Model):
    Module_CHOICES = (
        ('L', 'Lecture'),
        ('T', 'Test'),
    )
    module_type = models.CharField(max_length=1, blank=False, null=False, choices=Module_CHOICES, default='L')
    course = models.ForeignKey(Course, blank=False, null=False, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, blank=False, null=False)
    description = models.TextField()
    index = models.PositiveIntegerField(blank=False, null=False)

    class Meta:
        ordering = ['index']

    def __unicode__(self):
        return self.module_type + ' ' + self.title


class Lecture(Module):
    expected_hour = models.FloatField(null=True, blank=True)

    def __unicode__(self):
        return self.title


class Part(models.Model):
    Part_CHOICES = (
        ('R', 'Reading'),
        ('V', 'Video'),
        ('Q', 'Quiz'),
    )

    title = models.CharField(max_length=255, blank=False, null=False)
    description = models.TextField()
    lecture = models.ForeignKey(Lecture, blank=False, null=False, on_delete=models.CASCADE)
    index = models.PositiveIntegerField(blank=False, null=False)
    expected_hour = models.FloatField(null=False, blank=False)
    part_type = models.CharField(max_length=1, choices=Part_CHOICES, blank=False, null=False, default='R')

    class Meta:
        ordering = ['index']

    def __unicode__(self):
        return self.part_type + ' ' + self.title


class Reading(Part):
    Reading_CHOICES = (
        ('P', 'PDF'),
        ('M', 'material'),
    )

    file = models.FileField(upload_to='readings', blank=True, null=True)
    material = RichTextUploadingField(blank=True)
    reading_type = models.CharField(max_length=1, choices=Reading_CHOICES, blank=False, null=False, default='P')

    def __unicode__(self):
        return self.title


class Video(Part):
    link = models.TextField(blank=False,null=False)

    def __unicode__(self):
        return self.title


class Quiz(Part):
    full_score = models.PositiveIntegerField()

class Test(Module):
    expected_hour = models.FloatField(null=False, blank=False)
    full_score = models.PositiveIntegerField()

    def __unicode__(self):
        return self.title

class Question(models.Model):
    QUESTION_CHOICES = (
        ('MC', 'Multiple Choice'),
        ('BF', 'Blank Filled'),
    )
    quiz = models.ForeignKey(Quiz, blank=True, null=True, related_name='questions')
    test = models.ForeignKey(Test, blank=True, null=True, related_name='questions')
    index = models.PositiveIntegerField()
    weight = models.PositiveIntegerField(validators=[MaxValueValidator(100)])
    description = models.TextField(max_length=1000)
    image = models.ImageField(upload_to='question_image',blank=True, null=True)
    type = models.CharField(max_length=2, choices=QUESTION_CHOICES, blank=False, null=False, default='MC')

    def __unicode__(self):
        return self.description

    def delete(self):
        if self.quiz:
            upper_index = Question.objects.filter(quiz_id__exact=self.quiz_id, index__gt=self.index)
            if upper_index:
                for question in upper_index:
                    question.index = question.index - 1
                    question.save()
        if self.test:
            upper_index = Question.objects.filter(test_id__exact=self.test_id, index__gt=self.index)
            if upper_index:
                for question in upper_index:
                    question.index = question.index - 1
                    question.save()
        super(Question, self).delete()

class MCQuestion(Question):
    pass

class Choice(models.Model):
    mcquestion = models.ForeignKey(MCQuestion, related_name='choices')
    content = models.CharField(max_length=255)
    correct = models.BooleanField(default=False)

    def __unicode__(self):
        return self.content

class BFQuestion(Question):
    pass

class BFQuestionAnswer(models.Model):
    bfquestion = models.ForeignKey(BFQuestion)
    answer = models.CharField(max_length=255)

    def __unicode__(self):
        return self.answer

class UserProgressCourse(models.Model):
    user = models.ForeignKey(User)
    course = models.ForeignKey(Course)
    completed = models.BooleanField(default=False)
    module_completed = models.ManyToManyField(Module, related_name="completed_module")


class UserProgressModule(models.Model):
    user = models.ForeignKey(User)
    lecture = models.ForeignKey(Lecture)
    completed = models.BooleanField(default=False)
    part_completed = models.ManyToManyField(Part, related_name="completed_part")


class UserAnswer(models.Model):
    user = models.ForeignKey(User)
    question = models.ForeignKey(Question)
    TYPE_CHOICES = (
        ('MC', 'Multiple Choice'),
        ('BF', 'Blank Filled'),
    )
    type = models.CharField(max_length=2, choices=TYPE_CHOICES)
    answer = models.CharField(max_length=255, blank=True)

    def __unicode__(self):
        return self.answer

class UserAnswerUnsubmit(models.Model):
    user = models.ForeignKey(User)
    quiz = models.ForeignKey(Quiz, blank=True, null=True)
    test = models.ForeignKey(Test, blank=True, null=True)
    unsubmit = models.BooleanField(default=False)

class Grade(models.Model):
    user = models.ForeignKey(User)
    quiz = models.ForeignKey(Quiz, blank=True, null=True)
    test = models.ForeignKey(Test, blank=True, null=True)
    grade = models.IntegerField(default=0)

class UserProfile(models.Model):
    user = models.OneToOneField(User, blank=False, null=False, on_delete=models.CASCADE)
    bio = models.TextField()

class StudentNote(models.Model):
    user = models.ForeignKey(User, blank=True, null=True)
    lecture = models.ForeignKey(Lecture, blank=True, null=True)
    note = RichTextUploadingField(blank=True, null=True, default='')

src/webapps/cognita/templates/cognita/base.html
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>

    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS -->
    {% load static %}
    <link href='{% static 'css/bootstrap.min.css' %}' rel='stylesheet'>
    <link href='{% static 'css/base.css' %}' rel='stylesheet'>

    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.css' %}">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src='{% static 'js/jquery-3.2.1.min.js' %}'></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src='{% static 'js/bootstrap.js' %}'></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/creator/base.js' %}"></script>
    {% block head %}
    {% endblock %}
</head>
<body>

<nav class='navbar navbar-default navbar-fixed-top navbar-inverse' role='navigation'>
    <div class='container'>
        <div class='navbar-header'>
            <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-ex1-collapse'>
                <span class='sr-only'>Toggle navigation</span>
                <span class='icon-bar'></span>
                <span class='icon-bar'></span>
                <span class='icon-bar'></span>
            </button>
            <a class='navbar-brand' href='{% url 'home' %}'>Cognita</a>
        </div>

        <div class='collapse navbar-collapse navbar-ex1-collapse'>

            <ul class='nav navbar-nav'>
                <li><a href='{% url 'home' %}'>Home</a></li>
                <li><a href='{% url 'self_profile' %}'>My Profile</a></li>
            </ul>

            <div class='col-sm-3 col-md-3'>
                <form class='navbar-form' role='search' action="{% url 'search' %}" method="get">
                    <div class='input-group'>
                        <div class="ui-widget">
                        <input type='text' class='form-control ui-autocomplete' placeholder='Search' name='srch-term' id='srch-term'>
                        </div>
                            <div class='input-group-btn'>
                            <button class='btn btn-default' type='submit'><i class='glyphicon glyphicon-search'></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <ul class='nav navbar-nav navbar-right'>
                <li>
                    <a href='{% url 'add_course' %}'>Create Course</a>
                </li>
                <li class='dropdown'>
                    <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-haspopup='true'
                       aria-expanded='false'>{{ request.user.username }} <span class='caret'></span></a>
                    <ul class='dropdown-menu'>
                        <li><a href='{% url 'self_profile' %}'>View Profile</a></li>
                        <li role='separator' class='divider'></li>
                        <li class='dropdown-header'>Action</li>
                        <li><a href='{% url 'logout' %}'>Log out</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}


</body>
</html>

src/webapps/cognita/templates/cognita/creator/add_course.html
{% extends "cognita/base.html" %}
{% load static %}
{% block title %}
Add Course
{% endblock title %}

{% block body %}
    <div class="container base">
    <div class="col-md-8 col-md-offset-2">
        <h2>
            Adding a New Course
        </h2>
        <form enctype="multipart/form-data" action="{% url 'add_course' %}" class="single-form" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
                <p class="error_remind">{{ error }}</p>
            {% endfor %}


            {% for field in form %}
                <div class="form-group">
                {{ field.label_tag }}<br>
                {{ field }}
                </div>
                {% for error in field.errors %}
                    <p class="error_remind">{{ error }}</p>
                    {% endfor %}
            {% endfor %}




            <br>
            <div class="row save-button-small">



                <input type="submit" class="btn btn-default" value="Save">

            </div>


        </form>
    </div>


</div>
{% endblock body %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/creator.css' %}">



{% endblock head %}

src/webapps/cognita/templates/cognita/creator/course_search.html
{% spaceless %}
{% load static %}
{% for course in course_list %}
    <div class='result-content'>
        <div class='media'>
            <div class='media-left'>
                <a href='{% url 'course_page' course.id %}'>
                    {% if course.course_image %}
                        <img src='{% url 'course_img' course.id %}' class='media-object photo' alt='Course Photo'>
                    {% else %}
                        <img src='{% static 'images/course_default.png' %}' class='media-object photo'>
                    {% endif %}
                </a>
            </div>
            <div class='media-body post-text'>
                <a href='{% url 'course_page' course.id %}'><p class='course-result'>{{ course.title }}</p></a>
                <a href='{% url 'instructor' request.user.id %}'><p class='creator'>Creator: {{ course.creator }}</p></a>
                <div>
                            <span class='catagory-result'>{{ course.category }}</span>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
{% endspaceless %}

src/webapps/cognita/templates/cognita/creator/single_tag.html
<span class='tag' name='{{ tag.id }}'>{{ tag.tag_content }}<a class='delete-tag'><span class='glyphicon glyphicon-remove'></span></a></span>

src/webapps/cognita/templates/cognita/student/course_content.html
{% if not taking %}
    {% for module in modules %}
        <li class='list-group-item'>
                Module {{ module.index }}. {{ module.title }}
        </li>
    {% endfor %}
{% else %}
    {% for module in modules %}
        {% if module.module_type == 'L' %}
            <li class='list-group-item'>
                <a data-toggle='collapse' data-target='#module{{ module.index }}' id="expand-link{{ module.index }}">Module {{ module.index }}. {{ module.title }}</a>
                <span class='caret'></span>
                <span>Expected hours: {{ module.lecture.expected_hour }}</span>
                <div class='right btn-group' role='group' aria-label='Controls'>
					    <button type='button' class='btn btn-success toggle-note'
                                id="toggle-note-button{{ module.index }}"
                                onclick="toggle_note({{ module.index }})">Show Notes</button>
                    </div>
            </li>
            <div class='row-main row collapse' id='module{{ module.index }}'>
                <div class='col-sm-12 part-content' id="content{{ module.index }}">

                    <ol class='part-list'>
                        <h4>Learning goal:</h4>
                        <div class='description'>{{ module.description }}</div>
                    </ol>
                    <ol class='part-list'>
                        {% for part in module.lecture.part_set.all|dictsort:'index' %}
                            <li class='list-group-item part-list-height'>
                                {% if part.part_type == 'Q' %}
                                    <span class='glyphicon glyphicon-question-sign quiz-ic'></span>
                                    <span><a href='{% url 'auto_grade_quiz' part.quiz.id %}'>Quiz: {{ part.title }}</a></span>
                                {% else %}
                                    <span><a data-toggle='collapse' data-target='#module{{ module.index }}part{{ part.index }}'>
                                        {% if part.part_type == 'R' %}
                                            <span
                                                        class='glyphicon glyphicon-list-alt read-ic'></span>
                                            Reading: {{ part.title }}
                                        {% elif part.part_type == 'V' %}
                                            <span
                                                        class='glyphicon glyphicon-play-circle video-ic'></span>
                                            Video: {{ part.title }}
                                        {% endif %}
                                    </a></span>
                                    <span class='caret'></span>
                                {% endif %}
                                <span class='inline-form' id='progress_form_{{ part.id }}'>
                                    {% for pair in  progress_list%}
                                        {% if pair.0 == part.id%}
                                            {% if pair.1 == 0 %}
                                                {% if part.part_type == 'Q' %}
                                                    <label class="btn btn-xs btn-success disabled quiz-prog-mark">Mark as Complete</label>
                                                {% else %}
                                                    <form>
                                                        <input id='progress_part_{{ part.id }}' type='hidden' name='part' value='{{ part.id }}'>
                                                        <input id='progress_button_{{ part.id }}' class='btn btn-xs btn-success mark-progress' type='submit' value='Mark as Complete'>
                                                    </form>
                                                {% endif %}
                                            {% else %}
                                                {% if part.part_type == 'Q' %}
                                                    <label class="btn btn-xs btn-default disabled quiz-prog-mark">Completed</label>
                                                {% else %}
                                                    <form>
                                                        <input id='progress_part_{{ part.id }}' type='hidden' name='part' value='{{ part.id }}'>
                                                        <input id='progress_button_{{ part.id }}' class='btn btn-xs btn-default mark-progress' type='submit' value='Completed'>
                                                    </form>
                                                {% endif %}

                                            {% endif %}
                                        {% endif %}
                                    {% endfor %}
                                </span>
                                <span class='list-text'>
                                    {{ part.expected_hour }} hours
                                </span>
                            </li>
                            <div class='collapse' id='module{{ module.index }}part{{ part.index }}'>
                                {% if part.part_type == 'R' %}
                                    <div class='description'>{{ part.description }}</div>
                                    {% if part.reading.reading_type == 'P' %}
                                        <object  width=100% height='550px' data='{% url 'view_course_reading' part.reading.id %}'></object>
                                    {% elif part.reading.reading_type == 'M'%}
                                        <div class="reading-material">
                                            {{ part.reading.material|safe }}
                                        </div>
                                    {% endif %}
                                {% elif part.part_type == 'V' %}
                                    <div class='description'>{{ part.description }}</div>
                                    <iframe width=100% height='500px'
                                            src={{ part.video.link }} frameborder='0' allowfullscreen></iframe>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </ol>
                </div>
                <div class='note' id='note_{{ module.lecture.id }}'>

                </div>
            </div>
        {% else %}
            <li class='list-group-item'>
                <a href='{% url 'auto_grade_test' module.test.id%}'>Module {{ module.index }}. {{ module.title }}</a>
                <span>Expected hours: {{ module.test.expected_hour }}</span>
            </li>
        {% endif %}
    {% endfor %}
{% endif %}

src/webapps/cognita/templates/cognita/users/instructor_profile.html
{% extends 'cognita/base.html' %}
{% block title %}
    {{ instructor.first_name }}
{% endblock %}

{% block head %}
    {% load static %}
    <link href='{% static 'css/users.css' %}' rel='stylesheet'>
{% endblock %}

{% block body %}
    <div class='container'>
        <div class='row'>
            <div class='col-sm-3'>
                <h3>{{ instructor.first_name }} {{ instructor.last_name }}'s Courses</h3>
                <ul class='list-group'>
                    {% for course in courses %}
                        <li class='list-group-item'>
                            <b><a href='/course/{{ course.id }}'>{{ course.title }}</a></b>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class='col-sm-9'>
                <h3>Course Details</h3>
                <ul class='list-group'>
                    {% for course in courses %}
                        <li class='list-group-item'>
                            <h3><a href='/course/{{ course.id }}'>{{ course.title }}</a></h3>
                            <b>Category: </b>
                            <p>{{ course.get_category_display }}</p>
                            <b>Instructor Introduction</b>
                            <p>{{ course.creator_info }}</p>
                            <b>Course Introduction</b>
                            <p>{{ course.description }}</p>
                            <b>Number of students: </b>{{ course.students.count}}
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

src/webapps/cognita/templates/cognita/xinyangg/question_choice_answer_form.html
<div class="question_form" id="question_form">
    {% if error_message %}
        <div class="error_message">
            <p><strong>{{ error_message }}</strong></p>
        </div>
    {% endif %}
    {% if choice_forms %}
        <div id="all_choice">
            {% for letter, choice_form in choice_forms.items %}
                <div id="{{ choice_form.instance.id }}" class="form-group choice">
                    <button class="btn btn-success delete_choice">Delete</button>
                    <label class="choice-label">Choice {{ letter }} :</label>{{ choice_form.content }}
                    <input type="checkbox" name="choice_correct"
                            {% if letter in all_correct_choice %} checked {% endif %}
                           value="{{ letter }}">
                    <label class="mark_label">Mark as correct</label>
                </div>
                {% if choice_form.errors %}
                    <div class="val_error">
                        <p><strong>{{ choice_form.content.errors }}</strong></p>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <button class="btn btn-primary add_choice_button" type="button" id="add_choice_button"
                onclick="add_choice()" href="javascript:void(0)">Add another choice
        </button>
    {% endif %}
    {% if answer_forms %}
        <div id="correct_answer">
            {% for answer_form in answer_forms %}
                <div class="form-group answer" id="{{ answer_form.instance.id }}">
                    <button class="btn btn-success delete_answer">Delete</button>&nbsp;<label>Correct
                    Answer: </label>{{ answer_form.answer }}
                </div>
                {% if answer_form.errors %}
                    <div class="val_error">
                        <p><strong>{{ answer_form.answer.errors }}</strong></p>
                    </div>
                {% endif %}
            {% endfor %}

        </div>
        <button type="button" id="id_answer" href="javascript:void(0)"
                    onclick="add_correct_answer()" class="btn btn-primary add_answer_button">Add another correct answer
            </button>
    {% endif %}
</div>

src/webapps/cognita/templates/cognita/xinyangg/update_question.html
{% extends 'cognita/base.html' %}
{% block title %}
    Update Question
{% endblock %}
{% block head %}
    {% load static %}
    <link href="{% static 'css/create_update_question.css' %}" rel="stylesheet">
    <script src="{% static 'js/update_question.js' %}"></script>
    <script src="{% static 'js/bootstrap-confirmation.min.js' %}"></script>
{% endblock %}
{% block body %}
    <div class="container create_question_page">
        <div class="well">
            <h3>Update Question</h3>
            <form class="form-horizontal" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% if course %}
                    <div class="form-group"><label class="control-label">Course: {{ course }}</label>
                {% endif %}
                {% if lecture %}
                    <br>
                    <label class="control-label">Quiz: {{ quiz }}</label>
                {% else %}
                    <br>
                    <label class="control-label">Test: {{ test }}</label>
                {% endif %}
                </div>
                {% include 'cognita/xinyangg/question_info_form.html' %}
                <div class="form-group">
                    <label class="control-label">Question Type:</label>
                    {% if choices %}Multiple Choice{% endif %}
                    {% if answers %}Blank Filled{% endif %}
                </div>

                {% if choices %}
                     <div class="form-group">
                    <label class="control-label">Current Choices:</label>
                </div>

                {% if error_message %}
                    <div class="error_message">
                        <p><strong>{{ error_message }}</strong></p>
                        <br>
                    </div>
                {% endif %}
                    <table id="question_form" class="table current_choice_list">
                        <col span="1" class="wide1">
                        <col span="1" class="wide2">
                        <col span="1" class="wide3">
                        <col span="1" class="wide4">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Correct</th>
                            <th>Choices</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody id="all_choice">
                        {% for letter, choice in choices.items %}
                            <tr id="{{ choice.id }}" class="choice">
                                <th scope="row">{{ letter }}</th>
                                <td>{% if letter in all_correct_choice %}<i class="glyphicon glyphicon-ok"></i>
                                {% else %}<i class="glyphicon glyphicon-remove"></i>{% endif %}</td>
                                <td>{{ choice.content }}</td>

                                <td>
                                    <a><button class="btn btn-primary btn-choice-answer btn-edit-choice" type="button">Edit</button></a>
                                    <button class="btn btn-success btn-choice-answer btn-delete-choice" data-toggle="confirmation" type="button">Delete</button>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <button class="btn btn-primary add_choice_button" type="button"
                            id="add_choice_button"
                            onclick="add_choice()" href="javascript:void(0)">Add another choice
                    </button>
                {% endif %}
                {% if answers %}
                     <div class="form-group">
                    <label class="control-label">Current Correct Answer:</label>
                </div>

                {% if error_message %}
                    <div class="error_message">
                        <p><strong>{{ error_message }}</strong></p>
                        <br>
                    </div>
                {% endif %}
                    <table id="question_form" class="table answer_table">
                        <col span="1" class="answer_wide1">
                        <col span="1" class="answer_wide2">
                        <col span="1" class="wide4">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Correct Answer</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody id="correct_answer">
                            {% for index, answer in answers.items %}
                                <tr class="answer" id="{{ answer.id }}">
                                <th scope="row">{{ index }}</th>
                                <td>{{ answer.answer }}</td>
                                    <td>
                                    <button class="btn btn-primary btn-choice-answer btn-edit-answer" type="button">Edit</button>
                                    <button class="btn btn-success btn-choice-answer btn-delete-answer" data-toggle="confirmation" type="button">Delete</button>
                                </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <button type="button" id="id_answer" href="javascript:void(0)"
                            onclick="add_correct_answer()" class="btn btn-primary add_answer_button">Add another
                        correct answer
                    </button>
                {% endif %}

                <div class="add-button-group">
                    <button name="save" value="save" class="btn btn-add-question"> Save</button>

                    {% if lecture %}
                        <a href="{% url 'update_quiz' quiz.id %}">
                            <button type="button" class="btn btn-add-question">Back to quiz
                            </button>
                        </a>
                    {% else %}
                        <a href="{% url 'update_test' test.id %}">
                            <button type="button" class="btn btn-add-question">Back to test
                            </button>
                        </a>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
{% endblock %}